"use client";
import { useEffect, useMemo, useState } from "react";
import { Category, WorkRecord } from "@/lib/types";
import { cycleLabel, fiscalMonths, getEvaluationCycle, getThaiFiscalYear, thaiDate } from "@/lib/fiscal";

type PageName = "dashboard" | "records" | "categories";
const apiHeaders = (password: string) => ({ "Content-Type": "application/json", "x-app-password": password });

export default function Home() {
  const [password,setPassword]=useState(""); const [authenticated,setAuthenticated]=useState(false);
  const [page,setPage]=useState<PageName>("dashboard"); const [records,setRecords]=useState<WorkRecord[]>([]); const [categories,setCategories]=useState<Category[]>([]);
  const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const currentFY=getThaiFiscalYear(); const [fy,setFy]=useState(currentFY); const [cycle,setCycle]=useState(""); const [categoryFilter,setCategoryFilter]=useState(""); const [search,setSearch]=useState("");
  const [recordModal,setRecordModal]=useState<Partial<WorkRecord>|null>(null); const [categoryModal,setCategoryModal]=useState<Partial<Category>|null>(null);

  async function load(p=password){setLoading(true);setError("");try{const [r,c]=await Promise.all([fetch("/api/records",{headers:apiHeaders(p)}),fetch("/api/categories",{headers:apiHeaders(p)})]);if(r.status===401||c.status===401)throw new Error("รหัสผ่านไม่ถูกต้อง");if(!r.ok||!c.ok)throw new Error("เชื่อมต่อ Google Sheets ไม่สำเร็จ");setRecords(await r.json());setCategories(await c.json());setAuthenticated(true);sessionStorage.setItem("appPassword",p)}catch(e){setError(e instanceof Error?e.message:"เกิดข้อผิดพลาด");setAuthenticated(false)}finally{setLoading(false)}}
  useEffect(()=>{const p=sessionStorage.getItem("appPassword");if(p){setPassword(p);load(p)}},[]);

  const years=useMemo(()=>Array.from(new Set([currentFY,...records.map(r=>r.fiscalYear)])).filter(Boolean).sort((a,b)=>b-a),[records,currentFY]);
  const yearRecords=useMemo(()=>records.filter(r=>r.fiscalYear===fy),[records,fy]);
  const filtered=useMemo(()=>records.filter(r=>r.fiscalYear===fy&&(!cycle||r.cycle===cycle)&&(!categoryFilter||r.categoryId===categoryFilter)&&(!search||`${r.title} ${r.details} ${r.categoryName}`.toLowerCase().includes(search.toLowerCase()))),[records,fy,cycle,categoryFilter,search]);
  const completeCount=yearRecords.filter(r=>r.title&&r.categoryId&&r.startDate&&r.endDate&&r.details&&r.evidenceUrl).length;
  const completeness=yearRecords.length?Math.round(completeCount/yearRecords.length*100):0;

  if(!authenticated)return <div className="login"><div className="card login-card"><h1>ระบบจัดเก็บผลการปฏิบัติงาน</h1><p className="muted">เข้าสู่ระบบด้วยรหัสผ่านที่กำหนดใน Vercel</p><div className="field"><label>รหัสผ่าน</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="APP_PASSWORD"/></div>{error&&<p className="error">{error}</p>}<button className="btn primary" style={{width:'100%',marginTop:14}} onClick={()=>load()} disabled={loading}>{loading?'กำลังเชื่อมต่อ...':'เข้าสู่ระบบ'}</button></div></div>;

  async function saveRecord(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const body=Object.fromEntries(form.entries()) as any;body.id=recordModal?.id;body.fiscalYear=Number(body.fiscalYear);const method=recordModal?.id?'PUT':'POST';const res=await fetch('/api/records',{method,headers:apiHeaders(password),body:JSON.stringify(body)});const data=await res.json();if(!res.ok)return alert(data.error||'บันทึกไม่สำเร็จ');setRecordModal(null);await load();}
  async function deleteRecord(id:string){if(!confirm('ยืนยันการลบผลงานนี้?'))return;const res=await fetch(`/api/records?id=${id}`,{method:'DELETE',headers:apiHeaders(password)});const d=await res.json();if(!res.ok)return alert(d.error);await load();}
  async function saveCategory(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget).entries()) as any;body.id=categoryModal?.id;body.active=true;const res=await fetch('/api/categories',{method:categoryModal?.id?'PUT':'POST',headers:apiHeaders(password),body:JSON.stringify(body)});const d=await res.json();if(!res.ok)return alert(d.error);setCategoryModal(null);await load();}
  async function deleteCategory(id:string){if(!confirm('ยืนยันการลบหมวดหมู่นี้?'))return;const res=await fetch(`/api/categories?id=${id}`,{method:'DELETE',headers:apiHeaders(password)});const d=await res.json();if(!res.ok)return alert(d.error);await load();}
  async function exportDocx(){const res=await fetch('/api/export',{method:'POST',headers:apiHeaders(password),body:JSON.stringify({fiscalYear:fy,cycle:cycle||undefined,categoryId:categoryFilter||undefined})});if(!res.ok){const d=await res.json();return alert(d.error)}const blob=await res.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`performance-${fy}-${cycle||'all'}.docx`;a.click();URL.revokeObjectURL(a.href)}

  return <div className="shell"><aside className="sidebar"><div className="brand">Performance Tracker<small>ระบบจัดเก็บผลการปฏิบัติงาน</small></div><nav className="nav"><button className={page==='dashboard'?'active':''} onClick={()=>setPage('dashboard')}>ภาพรวม</button><button className={page==='records'?'active':''} onClick={()=>setPage('records')}>จัดการผลงาน</button><button className={page==='categories'?'active':''} onClick={()=>setPage('categories')}>หมวดหมู่งาน</button></nav></aside><main className="main">
    <div className="topbar"><div className="title"><h1>{page==='dashboard'?'ภาพรวมผลการปฏิบัติงาน':page==='records'?'จัดการผลงาน':'จัดการหมวดหมู่งาน'}</h1><p>ปีงบประมาณไทยและรอบการประเมินคำนวณอัตโนมัติ</p></div><div className="toolbar"><select value={fy} onChange={e=>setFy(Number(e.target.value))}>{years.map(y=><option key={y} value={y}>ปีงบประมาณ {y}</option>)}</select><button className="btn" onClick={()=>load()}>รีเฟรช</button></div></div>
    {page==='dashboard'&&<Dashboard records={yearRecords} categories={categories} completeness={completeness} fy={fy} setCycle={setCycle} setCategoryFilter={setCategoryFilter} cycle={cycle} categoryFilter={categoryFilter} exportDocx={exportDocx}/>} 
    {page==='records'&&<><div className="card"><div className="toolbar"><input placeholder="ค้นหาผลงาน..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={cycle} onChange={e=>setCycle(e.target.value)}><option value="">ทุกรอบ</option><option value="1">รอบที่ 1 (ต.ค.–มี.ค.)</option><option value="2">รอบที่ 2 (เม.ย.–ก.ย.)</option></select><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">ทุกหมวดหมู่</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="btn primary" onClick={()=>setRecordModal({fiscalYear:fy,cycle:getEvaluationCycle(new Date())})}>+ เพิ่มผลงาน</button><button className="btn" onClick={exportDocx}>Export .docx</button></div><RecordTable records={filtered} edit={setRecordModal} del={deleteRecord}/></div></>}
    {page==='categories'&&<div className="card"><div className="toolbar"><button className="btn primary" onClick={()=>setCategoryModal({})}>+ เพิ่มหมวดหมู่</button></div><div className="table-wrap"><table><thead><tr><th>หมวดหมู่</th><th>คำอธิบาย</th><th>จำนวนผลงาน</th><th>จัดการ</th></tr></thead><tbody>{categories.map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.description||'-'}</td><td>{records.filter(r=>r.categoryId===c.id).length}</td><td><button className="btn" onClick={()=>setCategoryModal(c)}>แก้ไข</button> <button className="btn danger" onClick={()=>deleteCategory(c.id)}>ลบ</button></td></tr>)}</tbody></table></div></div>}
  </main>{recordModal&&<RecordForm value={recordModal} categories={categories} close={()=>setRecordModal(null)} save={saveRecord}/>} {categoryModal&&<CategoryForm value={categoryModal} close={()=>setCategoryModal(null)} save={saveCategory}/>}</div>
}

function Dashboard({records,categories,completeness,fy,setCycle,setCategoryFilter,cycle,categoryFilter,exportDocx}:{records:WorkRecord[];categories:Category[];completeness:number;fy:number;setCycle:(v:string)=>void;setCategoryFilter:(v:string)=>void;cycle:string;categoryFilter:string;exportDocx:()=>void}){
 const byMonth=fiscalMonths.map(m=>records.filter(r=>new Date(`${r.startDate}T00:00:00`).getMonth()+1===m.key).length);const max=Math.max(1,...byMonth);const latest=[...records].sort((a,b)=>b.startDate.localeCompare(a.startDate)).slice(0,5);
 return <><div className="grid stats"><div className="card stat"><div className="label">ผลงานปีงบประมาณ {fy}</div><div className="value">{records.length}</div></div><div className="card stat"><div className="label">ความครบถ้วนของข้อมูล</div><div className="value">{completeness}%</div><div className="progress"><span style={{width:`${completeness}%`}}/></div></div><div className="card stat"><div className="label">หมวดหมู่ที่มีผลงาน</div><div className="value">{new Set(records.map(r=>r.categoryId)).size}</div></div><div className="card stat"><div className="label">รอบประเมินปัจจุบัน</div><div className="value" style={{fontSize:20}}>{cycleLabel(getEvaluationCycle(new Date()))}</div></div></div><div className="grid two"><div className="card"><h3>จำนวนผลงานรายเดือน</h3><div className="bars">{byMonth.map((n,i)=><div className="bar" key={i}><b>{n}</b><i style={{height:`${Math.max(4,n/max*120)}px`}}/><small>{fiscalMonths[i].label}</small></div>)}</div></div><div className="card"><h3>ผลงานแยกตามหมวดหมู่</h3>{categories.map(c=>{const n=records.filter(r=>r.categoryId===c.id).length;return <div key={c.id} style={{marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between'}}><span>{c.name}</span><b>{n}</b></div><div className="progress"><span style={{width:`${records.length?n/records.length*100:0}%`}}/></div></div>})}</div></div><div className="grid two" style={{marginTop:16}}><div className="card"><h3>ผลงานล่าสุด</h3><div className="latest">{latest.length?latest.map(r=><div className="latest-item" key={r.id}><b>{r.title}</b><div className="muted">{r.categoryName} • {thaiDate(r.startDate)}</div></div>):<div className="empty">ยังไม่มีข้อมูล</div>}</div></div><div className="card"><h3>ส่งออกรายงาน Word</h3><div className="field"><label>รอบการประเมิน</label><select value={cycle} onChange={e=>setCycle(e.target.value)}><option value="">ทั้งหมด</option><option value="1">รอบที่ 1</option><option value="2">รอบที่ 2</option></select></div><div className="field" style={{marginTop:10}}><label>หมวดหมู่งาน</label><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">ทั้งหมด</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><button className="btn primary" style={{marginTop:14,width:'100%'}} onClick={exportDocx}>Export .docx</button></div></div></>
}
function RecordTable({records,edit,del}:{records:WorkRecord[];edit:(r:WorkRecord)=>void;del:(id:string)=>void}){return <div className="table-wrap"><table><thead><tr><th>ผลงาน</th><th>หมวดหมู่</th><th>ช่วงวันที่</th><th>รอบ</th><th>หลักฐาน</th><th>จัดการ</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td><b>{r.title}</b><div className="muted">{r.details?.slice(0,90)}{r.details?.length>90?'...':''}</div></td><td><span className="badge">{r.categoryName}</span></td><td>{thaiDate(r.startDate)}<br/>ถึง {thaiDate(r.endDate)}</td><td>{cycleLabel(r.cycle)}</td><td>{r.evidenceUrl?<a href={r.evidenceUrl} target="_blank">เปิดลิงก์</a>:'-'}</td><td><button className="btn" onClick={()=>edit(r)}>แก้ไข</button> <button className="btn danger" onClick={()=>del(r.id)}>ลบ</button></td></tr>)}</tbody></table>{!records.length&&<div className="empty">ไม่พบข้อมูล</div>}</div>}
function RecordForm({value,categories,close,save}:{value:Partial<WorkRecord>;categories:Category[];close:()=>void;save:(e:React.FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop"><form className="modal" onSubmit={save}><h2>{value.id?'แก้ไขผลงาน':'เพิ่มผลงาน'}</h2><div className="form-grid"><div className="field full"><label>ชื่อผลงาน *</label><input name="title" defaultValue={value.title} required/></div><div className="field"><label>หมวดหมู่งาน *</label><select name="categoryId" defaultValue={value.categoryId||''} required><option value="">เลือกหมวดหมู่</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>ปีงบประมาณ *</label><input name="fiscalYear" type="number" defaultValue={value.fiscalYear||getThaiFiscalYear()} required/></div><div className="field"><label>วันเริ่มต้น *</label><input name="startDate" type="date" defaultValue={value.startDate} required/></div><div className="field"><label>วันสิ้นสุด *</label><input name="endDate" type="date" defaultValue={value.endDate} required/></div><div className="field"><label>รอบการประเมิน *</label><select name="cycle" defaultValue={value.cycle||'1'}><option value="1">รอบที่ 1 (ต.ค.–มี.ค.)</option><option value="2">รอบที่ 2 (เม.ย.–ก.ย.)</option></select></div><div className="field"><label>ลิงก์หลักฐาน</label><input name="evidenceUrl" type="url" defaultValue={value.evidenceUrl} placeholder="https://..."/></div><div className="field full"><label>รายละเอียด / ผลสัมฤทธิ์</label><textarea name="details" defaultValue={value.details}/></div></div><div className="actions"><button type="button" className="btn" onClick={close}>ยกเลิก</button><button className="btn primary">บันทึก</button></div></form></div>}
function CategoryForm({value,close,save}:{value:Partial<Category>;close:()=>void;save:(e:React.FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop"><form className="modal" onSubmit={save}><h2>{value.id?'แก้ไขหมวดหมู่':'เพิ่มหมวดหมู่'}</h2><div className="field"><label>ชื่อหมวดหมู่ *</label><input name="name" defaultValue={value.name} required/></div><div className="field" style={{marginTop:12}}><label>คำอธิบาย</label><textarea name="description" defaultValue={value.description}/></div><div className="actions"><button type="button" className="btn" onClick={close}>ยกเลิก</button><button className="btn primary">บันทึก</button></div></form></div>}
